'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n-1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n-1)      1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

import math


def is_pentagonal_number(x):
    n = (1.0 + math.sqrt(1 + 24 * x)) / 6.0
    return n == int(n)


def is_hexagonal_number(x):
    n = (1.0 + math.sqrt(1 + 8 * x)) / 4.0
    return n == int(n)


def get_triangle_number(n):
    return n * (n + 1) / 2


n = 286

while(True):
    x = get_triangle_number(n)
    if is_hexagonal_number(x) and is_pentagonal_number(x):
        print 'result: ', n, x
        break
    n += 1
